In [1]:
import numpy as np

# Vector Creation

In [5]:
a = np.zeros(4);
b = np.zeros(4,);
c = np.random.random_sample(5)
d = np.ones(5)
print(a)
print(b)
print(c)
print(d)
print(c.T)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0.68542469 0.33353641 0.92024729 0.28848468 0.45556283]
[1. 1. 1. 1. 1.]
[0.68542469 0.33353641 0.92024729 0.28848468 0.45556283]


In [6]:
a = np.array([[3,4,5], [4,5,6], [13,14,15], [40,50,60]])
print(a.shape)
b = np.array([1,2,3])
print(b.shape)

(4, 3)
(3,)


# Vector Operations

In [7]:
a = np.arange(10)
print(a)
print(type(a))

# access an element
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}")
print(a[-1])

try:
    c = a[10]
except Exception as e:
    print("Error: ", e)

c = a[2:7:1];   print(f"a[2:7:2] = {c}")
d = a[2:7:2]; print(f"a[2:7:2] = {d}") # Steps

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
a[2].shape: () a[2] = 2
9
Error:  index 10 is out of bounds for axis 0 with size 10
a[2:7:2] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]


In [8]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

b = np.max(a)
print(f"b = np.max(a)  : {b}")

b = np.square(a)
print(f"b = np.square(a) = {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]
b = np.max(a)  : 4
b = np.square(a) = [ 1  4  9 16]


In [9]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")
print(f"np.add(a, b) = {np.add(a, b)}")

Binary operators work element wise: [0 0 6 8]
np.add(a, b) = [0 0 6 8]


# Scalar Vector Operations

In [ ]:
a = np.array([1,2,3,4])
print(f"shape of a: {a.shape}, type: {type(a)}")
b = 5 * a
print(b)
c = a * 5
print(c)

shape of a: (4,), type: <class 'numpy.ndarray'>
[ 5 10 15 20]
[ 5 10 15 20]


In [ ]:
# Dot Product
def my_dot(a, b):
    dot = 0
    for i in range(a.shape[0]):
        dot += a[i] * b [i]
    return dot
a = np.array([1,2,3,4])
b = np.array([1,1,1,1])
print(f"Dot product of a and b: {my_dot(a, b)}")

Dot product of a and b: 10


In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,1,1,1])
d = np.dot(a, b)
print(f"Dot product of a and b: {d}")

Dot product of a and b: 10


# Vectorization

In [ ]:
import time

np.random.seed(1)
a = np.random.rand(100000000) # Very large arrays
b = np.random.rand(100000000)
print(a, b)
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms")

tic = time.time()
c = my_dot(a, b)
toc = time.time()
print(f"loop version duration: {1000*(toc-tic):.4f} ms")

[4.17022005e-01 7.20324493e-01 1.14374817e-04 ... 6.28539888e-01
 2.18602350e-01 5.49886629e-01] [0.41998369 0.38713495 0.00665417 ... 0.42359362 0.15733362 0.91064571]
Vectorized version duration: 136.3046 ms
loop version duration: 25099.5822 ms


# Broadcasting example

In [11]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [14]:
cal = A.sum(axis=0) # Sum the columns vertically, = 1 for horizontal summation
print(cal)
print(cal.reshape(1,4))

_mean = A.mean(axis=0)
print(f"Mean of columns")
print(f"{_mean}")

[ 59.  239.  155.4  76.9]
[[ 59.  239.  155.4  76.9]]
Mean of columns
[19.66666667 79.66666667 51.8        25.63333333]


In [ ]:
total_calories = cal.reshape(1, 4)
percentage = 100 * A / total_calories
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [ ]:
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
second_matrix = np.array([[100, 200, 300]])
print(first_matrix + second_matrix)

[[101 202 303]
 [104 205 306]]


In [ ]:
first_matrix = np.array([[1,2,3], [4,5,6]])
second_matrix = np.array([[100], [200]])
print(first_matrix + second_matrix)

[[101 102 103]
 [204 205 206]]


In [ ]:
a = np.random.randn(5)
print(a)

[-1.64875564  0.96840418  0.6251876  -0.07901316 -1.91696625]


In [ ]:
print(a.shape) # Rank 1 array

(5,)


In [ ]:
a = np.random.randn(5,1)
print(a)
print(a.shape)
print(a.T)

[[ 0.6078807 ]
 [-1.45991477]
 [ 0.916621  ]
 [-0.93416089]
 [-0.2491129 ]]
(5, 1)
[[ 0.6078807  -1.45991477  0.916621   -0.93416089 -0.2491129 ]]


In [ ]:
print(np.dot(a, a.T))
print(np.dot(a.T, a))

[[ 0.38243521  0.04897894 -0.6641783  -1.4964814   0.38812938]
 [ 0.04897894  0.00627279 -0.08506212 -0.19165619  0.0497082 ]
 [-0.6641783  -0.08506212  1.1534838   2.59895128 -0.67406741]
 [-1.4964814  -0.19165619  2.59895128  5.85578034 -1.51876287]
 [ 0.38812938  0.0497082  -0.67406741 -1.51876287  0.39390833]]
[[7.79188047]]


In [ ]:
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551],
                     [ 0.90714982,  0.52835647]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313],
                    [ 0.90714982,  0.52835647]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077],
                    [ 0.90714982,  0.52835647]]])

In [ ]:
print(t_image.shape)

(3, 4, 2)


In [ ]:
print(t_image.shape[0])
print(t_image.shape[1])
print(t_image.shape[2])

3
4
2


In [ ]:
print(t_image[0])

[[0.67826139 0.29380381]
 [0.90714982 0.52835647]
 [0.4215251  0.45017551]
 [0.90714982 0.52835647]]


# Normalization

In [15]:
x = np.array([[0., 3., 4.],
              [1., 6., 4.]])
# axis=1 => horizontal, axis=0 => vertical
x_norm = np.linalg.norm(x, axis=1)
print(x_norm)
x_norm = np.linalg.norm(x, axis=1, keepdims=True)
print(x_norm)
print(x / x_norm)

[5.         7.28010989]
[[5.        ]
 [7.28010989]]
[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


# Softmax



In [ ]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])

x_exp = np.exp(t_x)
x_sum = np.sum(x_exp, axis=1, keepdims=True)
x_softmax = x_exp / x_sum
print(x_softmax)

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
